### PR TITLE
feat(esp32c5): Add stub flasher support

### PR DESCRIPTION
**Pull request by Dzarda7**
### Overview
This pull request adds stub support for ESP32C5. It adds both  UART and USB-serial/JTAG stub support. The support was already added into esptool recently.

### Related
Relates to ESPTOOL-825

### CODE REVIEW

**Comment by Dzarda7** [comment]
@dobairoland PTAL

**Comment by dobairoland** [comment]
Changes LGTM. I would like to rebase this after https://github.com/espressif/esptool-legacy-flasher-stub/pull/6 and compare the JSON file from the artifacts with the one from the esptool repository.

**Comment by dobairoland** [comment]
@Dzarda7 Could you please rebase this? Not all github actions were started here (my mistake!). I've created and merged a fix in the meantime.

**Comment by Dzarda7** [comment]
@dobairoland done. Thanks.

**Review by dobairoland — APPROVED** [review]
LGTM. Thank you @Dzarda7.

I also checked that the binaries from the artifacts are the same as the ones in the latest esptool master branch (C5 and C5beta3 included).

**Review by radimkarnis — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
